name: Obsidian Vault Backup

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'myblog/**'
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Backup Vault
        run: |
          git add --all
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Auto-backup: $(date +'%Y-%m-%d %H:%M:%S')"
          git push

